### ISSUE TITLE
Unit summary table in two places now

### ISSUE THREAD

**Issue by jaredcwhite** [Exygy/bloom#15]
Looks like it got merged in separate locations in the markup, so we should decide where the best location is…

https://github.com/Exygy/affordablehousing-x/blob/4345b092a3ebb85eda185c3239ef590ed94735ae/apps/public/pages/listing.tsx#L86

**Comment by bk3c** [comment]
Yeah, that's probably my merge error. @jaredcwhite which set of styling is correct?

**Comment by jaredcwhite** [comment]
@bk3c We could probably go either way. Thoughts @callaghanc ?

**Comment by jaredcwhite** [comment]
Appears to be fixed in master now.
