### ISSUE TITLE
Use UUIDs to refer to listings and other key objects

### ISSUE THREAD

**Issue by bk3c** [Exygy/bloom#18]
As we start having interdependencies between services that don't share the same database, it's going to be important to have stable, universal, readable IDs for any object in the system that will be persistently referenced outside of 1 backend service.

Some implementation options include:
- https://github.com/ai/nanoid (my preference)
- https://github.com/dylang/shortid
- https://github.com/kelektiv/node-uuid

**Comment by jaredcwhite** [comment]
Closed as part of #49
