### ISSUE TITLE
Add occupancy table to listing

### ISSUE THREAD

**Issue by callaghanc** [Exygy/bloom#37]
Add an occupancy table to the Occupancy subsection of the listing details Eligibility section.

Screencap of the original SF DAHLIA table that we need to recreate: <img width="683" alt="Screen Shot 2019-09-06 at 11 32 57 AM" src="https://user-images.githubusercontent.com/1117776/64452403-2887af80-d09b-11e9-8d74-e896daa02fa1.png">

**Comment by jaredcwhite** [comment]
Forgot to close this when #49 got merged in.
