### ISSUE TITLE
Add a responsive menu

### ISSUE THREAD

**Issue by callaghanc** [Exygy/bloom#39]
Create a responsive navbar menu.

<img width="1055" alt="Screen Shot 2019-09-10 at 11 12 45 AM" src="https://user-images.githubusercontent.com/1117776/64639950-d063ec80-d3bd-11e9-9613-efa0ad4aa1dc.png">
<img width="321" alt="Screen Shot 2019-09-10 at 11 13 35 AM" src="https://user-images.githubusercontent.com/1117776/64639951-d063ec80-d3bd-11e9-9e35-2302eebb8575.png">
<img width="323" alt="Screen Shot 2019-09-10 at 11 13 46 AM" src="https://user-images.githubusercontent.com/1117776/64639952-d063ec80-d3bd-11e9-888f-e20f3d5dd60b.png">

**Comment by exygy-dev** [comment]
Implementation notes from a team meeting:

- Let's see if we can get something off the shelf, if there's an existing react component that meets our needs
- Accessibility will be a primary concern here, along with flexibility going forward.
