### ISSUE TITLE
Calculate the unit summary data rather than hardcoding it

### ISSUE THREAD

**Issue by bk3c** [Exygy/bloom#54]
Right now the JSON files have the unit summaries hardcoded in them, but we should calculate this on the server side.

**Comment by software-project** [comment]
@bk3c I'm trying to figure out the best way to do this. And it got me to thinking if we really need grouped units and unit_summaries, as it feels like they are at least very similar. Am I missing something here?

**Comment by software-project** [comment]
reserved and priority will have the same structure as grouped
