### ISSUE TITLE
Add API tests for the listings service

### ISSUE THREAD

**Issue by bk3c** [Exygy/bloom#73]
Not for immediate work given the current amount of flux in the API, but in the future we should seek to have (I'm assuming) Jest tests of the service APIs directly, and then move the front-end tests to using fixed static inputs. Less value in the short term since we're using fixed static inputs for real, but as soon as we're not we'll need tests.

**Comment by software-project** [comment]
Initial part of this one is done @bk3c so I think we can close it.
